spring.servlet.multipart:
  max-file-size: 1280KB
  max-request-size: 1280KB

spring:
  h2.console.enabled: true
  datasource.url=jdbc:h2:mem: testdb
  data.jpa.repositories.bootstrap-mode: default


resilience4j.ratelimiter:
  instances:
    tickerService:
      limitForPeriod: 10
      limitRefreshPeriod: 10s
      timeoutDuration: 5
      registerHealthIndicator: true

resilience4j.bulkhead:
  instances:
    tickerService:
      maxWaitDuration: 1000ms
      maxConcurrentCall: 8

#resilience4j.thread-pool-bulkhead:
#  instances:
#    tickerService:
#      maxThreadPoolSize: 8
#      coreThreadPoolSize: 1
#      queueCapacity: 10